version: '3.8'

services:
  # Servicio de Laravel (backend)
  laravel-app:
    image: php:8.1-fpm
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./back:/var/www
    command: bash -c "apt-get update && apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev zip unzip git && docker-php-ext-configure gd --with-freetype --with-jpeg && docker-php-ext-install gd && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && composer install && php artisan serve --host=0.0.0.0 --port=8000"
    ports:
      - "8000:8000"
    networks:
      - app-network

  # Servicio de Nuxt.js (frontend)
  nuxt-app:
    image: node:16
    container_name: nuxt_app
    working_dir: /app
    volumes:
      - ./front:/app
    command: bash -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    networks:
      - app-network

  # Servicio de base de datos (MySQL)
  db:
    image: mysql:latest # Actualizado para usar la última versión de MySQL
    container_name: mysql_db
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpassword
    ports:
      - "3307:3306"
    networks:
      - app-network

  # Servicio de phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest # Actualizado para usar la última versión de phpMyAdmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
