# Establecer la imagen base. Node 14 es una versión LTS estable que podría ser utilizada.
FROM node:14

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar 'package.json' y 'package-lock.json' (si está disponible)
COPY package*.json ./

# Instalar dependencias del proyecto
RUN npm install

# Copiar los archivos y directorios restantes al directorio de trabajo
COPY . .

# Construir la aplicación para producción
RUN npm run build

# Exponer el puerto que Nuxt.js escuchará
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["npm", "start"]
